#!/bin/sh
# Inspired by https://github.com/aliem/containers/blob/master/base/dosu
[ $# -lt 2 ] && echo "Usage: dosu user command [args...]" >&2 && exit 1
user=$1
shift
cmd=exec
for i; do cmd="$cmd '$i'"; done
exec busybox su -s /bin/sh -c "$cmd" "$user"